# Generated by Django 5.2.5 on 2025-09-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monastery',
            name='vr_image',
            field=models.ImageField(blank=True, null=True, upload_to='monasteries/vr/'),
        ),
        migrations.AddField(
            model_name='monastery',
            name='vr_video',
            field=models.FileField(blank=True, null=True, upload_to='monasteries/vr/'),
        ),
    ]
