# Generated by Django 5.2.5 on 2025-09-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0002_monastery_vr_image_monastery_vr_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='monastery',
            name='streetview_embed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
